import Link from 'next/link';
import'./globals.css'

export const metadata = {
  title: 'Create Next App',
  descriotion: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body>
      <nav className="bg-blue-500">
    <ul>
        <li> <Link href="/">Home</Link>
        </li>
        <li> <Link href="/book">Book</Link>
        </li>
        <li> <Link href="/gibi">Gibi</Link>
        </li>
    </ul>
    </nav>
        {children}
        </body>
    </html>
  );
}
